### ISSUE TITLE
Linters

### ISSUE THREAD

**Issue by Max2288** [siriusdevs/rpm_library_7_1#1]
![image](https://user-images.githubusercontent.com/42071821/230596072-af2d39db-cd11-4318-ab9c-41a7d622eacf.png)
![image](https://user-images.githubusercontent.com/42071821/230596560-50d91d36-f4f6-4bac-9291-1509ba985d0d.png)

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230599031-6aa729c3-3370-46db-9861-fd9422c1c4c0.png)

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230599204-403a72e6-fd2c-45cf-bcda-a7dee94b1388.png)
not location ???? we don't need it

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230599299-c468b7dd-bac4-4986-a83a-4926cf86c4d5.png)
the same

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230599608-4ac99805-7d0b-418b-b1e5-0335918bbbe5.png)
 Too many conditions

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230600423-bc50592a-8e15-4aa8-a577-7bf1c849c9f4.png)

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230600652-c96c99a2-11dc-462b-ba0c-ab8adf271c56.png)

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230600892-d398cdad-b5a7-43d6-bfe4-3254531d4d0e.png)
spaces???

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230601101-6f8de41b-2d3d-4c00-aa67-9086f96d45e5.png)
![image](https://user-images.githubusercontent.com/42071821/230601125-ef3c6a8e-4779-4a04-9f74-8d2dc81ac7e8.png)
34 > 30

**Comment by Max2288** [comment]
![image](https://user-images.githubusercontent.com/42071821/230601413-08012df5-6057-42b7-a221-56ed039b3761.png)
![image](https://user-images.githubusercontent.com/42071821/230601491-854592c0-6ee7-4af2-80f1-91287b0aef80.png)

**Comment by siriusdevs** [comment]
![Screenshot from 2023-04-07 23-06-24](https://user-images.githubusercontent.com/102812997/230672247-3b2abdff-c9bd-449d-bb70-70af548fba51.png)

**Comment by siriusdevs** [comment]
> ![image](https://user-images.githubusercontent.com/42071821/230599031-6aa729c3-3370-46db-9861-fd9422c1c4c0.png)

fixed

**Comment by siriusdevs** [comment]
> ![image](https://user-images.githubusercontent.com/42071821/230599204-403a72e6-fd2c-45cf-bcda-a7dee94b1388.png) not location ???? we don't need it

fixed

**Comment by siriusdevs** [comment]
> ![image](https://user-images.githubusercontent.com/42071821/230599299-c468b7dd-bac4-4986-a83a-4926cf86c4d5.png) the same

response can be None here, we cannot chek attribute status code of None. it will raise an error

**Comment by siriusdevs** [comment]
> ![image](https://user-images.githubusercontent.com/42071821/230600652-c96c99a2-11dc-462b-ba0c-ab8adf271c56.png)

fixed

**Comment by siriusdevs** [comment]
> ![image](https://user-images.githubusercontent.com/42071821/230600892-d398cdad-b5a7-43d6-bfe4-3254531d4d0e.png) spaces???

why? works anyway.

**Comment by siriusdevs** [comment]
> ![image](https://user-images.githubusercontent.com/42071821/230601101-6f8de41b-2d3d-4c00-aa67-9086f96d45e5.png) ![image](https://user-images.githubusercontent.com/42071821/230601125-ef3c6a8e-4779-4a04-9f74-8d2dc81ac7e8.png) 34 > 30

fixed

**Comment by siriusdevs** [comment]
its all fun and games until someone gets banned cause he was making up silly issues during the lesson :eyes:  :kazakhstan:

**Comment by siriusdevs** [comment]
its all fun and games until someone gets banned cause he was making up silly issues during the lesson eyes kazakhstan
