### ISSUE TITLE
If he saw it, he would not fly into space

### ISSUE THREAD

**Issue by Max2288** [siriusdevs/rpm_library_7_1#2]
![image](https://user-images.githubusercontent.com/42071821/231455841-e3c26451-d619-4558-a01f-057cf3d25727.png)
![image](https://user-images.githubusercontent.com/42071821/231455869-9d166904-2517-4302-80d1-802477f67fca.png)

**Comment by siriusdevs** [comment]
one more issue and i will be at my limit :kazakhstan:
